'use client'

import { useEffect, useMemo, useState } from 'react'
import { Download, Eye, Search, Trash2 } from 'lucide-react'
import { bookingService, exportBookingsCsv } from '@/services/bookings/bookingService'
import { subscribeToStorageChanges } from '@/services/storage/storageService'
import { STORAGE_KEYS } from '@/services/storage/storageKeys'
import { useCurrency } from '@/hooks/useCurrency'
import { useLanguage } from '@/hooks/useLanguage'
import { formatDate } from '@/lib/utils'
import type { Booking, BookingStatus } from '@/types'
import { InvoiceButton } from '@/lib/invoice'

export function BookingTable() {
  const { t, locale, dir } = useLanguage(); const { format } = useCurrency()
  const [bookings, setBookings] = useState<Booking[]>([]); const [query, setQuery] = useState(''); const [status, setStatus] = useState<'all' | BookingStatus>('all'); const [selected, setSelected] = useState<Booking | null>(null)
  const refresh = () => setBookings(bookingService.list())
  useEffect(() => { refresh(); return subscribeToStorageChanges((key) => { if (key === STORAGE_KEYS.bookings) refresh() }) }, [])
  const filtered = useMemo(() => bookings.filter((booking) => `${booking.customerName} ${booking.customerEmail} ${booking.phone ?? ''} ${booking.tourTitle}`.toLowerCase().includes(query.toLowerCase()) && (status === 'all' || booking.status === status)), [bookings, query, status])
  const download = () => { const blob = new Blob([exportBookingsCsv(filtered)], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'egyptgo-bookings.csv'; anchor.click(); URL.revokeObjectURL(url) }
  return <section dir={dir} className="flex flex-col gap-5">
    <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-xl font-bold">Bookings</h2><p className="text-sm text-muted-foreground">Manage reservations without processing payments.</p></div><button onClick={download} className="inline-flex items-center justify-center gap-2 rounded-xl border border-border px-3 py-2 text-xs font-semibold hover:bg-muted"><Download className="size-4" /> Export CSV</button></div>
    <div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute start-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search customer, email, or tour" className="w-full rounded-xl border border-border bg-background py-3 ps-9 pe-3 text-sm" /></label><select value={status} onChange={(event) => setStatus(event.target.value as typeof status)} className="rounded-xl border border-border bg-background px-3 py-3 text-sm"><option value="all">All statuses</option><option value="confirmed">Confirmed</option><option value="pending">Pending</option><option value="cancelled">Cancelled</option></select></div>
    <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-border text-left text-[11px] uppercase tracking-wider text-muted-foreground"><th className="px-3 py-3">Booking</th><th className="px-3 py-3">Customer</th><th className="px-3 py-3">Date</th><th className="px-3 py-3">Value</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Actions</th></tr></thead><tbody>{filtered.map((booking) => <tr key={booking.id} className="border-b border-border/60"><td className="px-3 py-4"><button onClick={() => setSelected(booking)} className="text-left"><p className="font-semibold hover:text-accent">{booking.tourTitle}</p><p className="text-xs text-muted-foreground">{booking.id}</p></button></td><td className="px-3 py-4"><p>{booking.customerName}</p><p className="text-xs text-muted-foreground">{booking.customerEmail}</p><p className="text-xs text-muted-foreground">{booking.phone ? `${booking.phoneCountryCode ?? ''} ${booking.phone}`.trim() : 'Phone not provided'}</p></td><td className="px-3 py-4">{formatDate(booking.date, locale)}<p className="text-xs text-muted-foreground">{booking.travelers} travelers</p></td><td className="px-3 py-4 font-semibold">{format(booking.total)}<p className="text-xs font-normal text-muted-foreground">Pay locally</p></td><td className="px-3 py-4"><select value={booking.status} onChange={(event) => setBookings(bookingService.updateStatus(booking.id, event.target.value as BookingStatus))} className="rounded-full border border-border bg-background px-2 py-1 text-xs font-semibold"><option value="confirmed">Confirmed</option><option value="pending">Pending</option><option value="cancelled">Cancelled</option></select></td><td className="px-3 py-4"><div className="flex items-center gap-2"><button aria-label="View booking" onClick={() => setSelected(booking)} className="rounded-lg border border-border p-2 hover:bg-muted"><Eye className="size-4" /></button><InvoiceButton booking={booking} locale={locale} label={t('downloadInvoice')} /><button aria-label="Delete booking" onClick={() => { if (window.confirm('Are you sure? This cannot be undone.')) setBookings(bookingService.remove(booking.id)) }} className="rounded-lg border border-destructive/30 p-2 text-destructive hover:bg-destructive/10"><Trash2 className="size-4" /></button></div></td></tr>)}</tbody></table>{!filtered.length && <p className="py-10 text-center text-sm text-muted-foreground">No bookings match your filters.</p>}</div>
    {selected && <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 grid place-items-center bg-primary/30 p-4"><div className="w-full max-w-lg rounded-2xl bg-card p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-wider text-accent">Booking detail</p><h3 className="mt-1 text-xl font-bold">{selected.tourTitle}</h3></div><button onClick={() => setSelected(null)} className="text-sm text-muted-foreground">Close</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2 text-sm"><div><p className="text-muted-foreground">Customer</p><p className="font-semibold">{selected.customerName}</p><p>{selected.customerEmail}</p><p>{selected.phone ? `${selected.phoneCountryCode ?? ''} ${selected.phone}`.trim() : 'Phone not provided'}</p><p className="mt-1 text-muted-foreground">Country: {selected.countryNameEn ?? selected.countryCode ?? 'Not provided'}</p></div><div><p className="text-muted-foreground">Reference</p><p className="font-semibold">{selected.id}</p></div><div><p className="text-muted-foreground">Travel date</p><p>{formatDate(selected.date, locale)}</p></div><div><p className="text-muted-foreground">Travelers</p><p>{selected.travelers}</p></div><div><p className="text-muted-foreground">Booking value</p><p className="font-semibold">{format(selected.total)} · pay locally</p></div><div><p className="text-muted-foreground">Status</p><p className="font-semibold capitalize">{selected.status}</p></div></div></div></div>}
  </section>
}
